// Generated by CoffeeScript 1.3.3
(function() {
  var omd, path;

  path = require('path');

  omd = new (require("outline-markdown")).Omd;

  module.exports = function(app) {
    app.get('/docs/*', function(req, res, next) {
      var dstPath, params, srcFileParts, srcName, srcPath;
      params = req.route.params;
      if (!params[0]) {
        return next();
      } else {
        srcFileParts = params[0].split("/");
        srcName = path.join(app.get("docsSrcPath"), srcFileParts.join(path.sep) + '.omd');
        srcFileParts.pop();
        srcPath = srcFileParts.join(path.sep);
        dstPath = path.join(app.get("docsDstPath"), srcPath);
        omd.parse(srcName, dstPath, function(callback) {
          console.log('render', "docs/" + params[0]);
          return res.render("docs/" + params[0]);
        });
        return res.end();
      }
    });
    return app.get('/docs', function(req, res) {
      return res.render("docs/index", {
        title: "Docs"
      });
    });
  };

}).call(this);
